pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot[bot]
      - status-success=Build, Test and Release
    actions:
      merge:
        method: merge
