pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot-preview[bot]
      - status-success=Linting - Check Style
    actions:
      merge:
        method: merge
